name: proto1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  window_manager: ^0.3.7

dev_dependencies:
  analyzer: ^6.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.0.5
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
